### ISSUE TITLE
media volume mounted incorrectely

### ISSUE THREAD

**Issue by baloan** [NathanVaughn/webtrees-docker#120]
The media volume sits at ![image](https://user-images.githubusercontent.com/651799/218198952-cc52927d-53bb-4f6c-af6b-db44039f4cb4.png)
in my instance, so the media mount defined in the `docker-compose.yml` is never used. All media is written to `/var/www/webtrees/data/media`.
Is this intentional? Not sure whether I can change the media directory to the path recommended in the docker manual at all.
Here is an excerpt from the volume definiton from https://hub.docker.com/r/nathanvaughn/webtrees

```
    volumes:
      - data:/var/www/webtrees/data/
      - media:/var/www/webtrees/media/
      - themes:/var/www/webtrees/modules_v4/
```

**Comment by NathanVaughn** [comment]
This seems correct. With the `..` in there, it resolves to `/var/www/webtrees/data/media/`. That's covered under `/var/www/webtrees/data` so it gets saved. You really want to save the whole `/var/www/webtrees/data` directory, since that's where the `config.ini.php` file is written to that saves database information and other site settings.

I'll be honest, I have no idea what webtrees sticks on the `/var/www/webtrees/media` folder. My personal instance has nothing in it. It sounds important, hence why I recommend making sure it's a saved volume.
